Employee_Self_Service/Controllers/LeaveController.cs
using System.Security.Claims;
using System.Text.RegularExpressions;
using Employee_Self_Service.Authorization;
using Employee_Self_Service.Hubs;
using Employee_Self_Service_BAL.Interface;
using Employee_Self_Service_DAL.ViewModel;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.SignalR;
using Microsoft.EntityFrameworkCore;

namespace Employee_Self_Service.Controllers;

public class LeaveController : Controller
{
    private readonly ILeaveService _leaveService;
    private readonly IProfileService _profileService;
    private readonly IJwtService _jwtService;
    private readonly IHubContext<NotificationHub> _hubContext;

    public LeaveController(ILeaveService leaveService,IProfileService profileService,IJwtService jwtService,IHubContext<NotificationHub> hubContext)
    {
        _leaveService = leaveService;
        _profileService = profileService;
        _jwtService = jwtService;
        _hubContext = hubContext;
    }

    #region Employee Side Leave 
    public IActionResult LeaveRequest()
    {
        return View();
    }
    
    public async Task<IActionResult> GetRequestList(int pageSize, int pageNumber, string searchQuery, string sortColumn, string sortDirection, string leaveRequestFromDate, string leaveRequestToDate, string leaveRequestStatus,int employeeId)
    {   
        var model = await _leaveService.GetRequestData(pageSize, pageNumber, searchQuery, sortColumn, sortDirection, leaveRequestFromDate, leaveRequestToDate, leaveRequestStatus, employeeId);
        return PartialView("_LeaveRequestListPartialView", model);
    }
    [HttpGet]
    public async Task<ActionResult> AddEditLeaveRequest(int requestId)
    {   
        var token = _jwtService.ValidateToken(Request.Cookies["token"]);
        var email = token?.Claims.FirstOrDefault(c => c.Type == ClaimTypes.Email)?.Value;
        if (email == null)
        {
           TempData["errorToastr"] = "Email not found.";
           return RedirectToAction("Index", "Home");
        } 
        AddLeaveRequestViewModel model = new AddLeaveRequestViewModel();
        if (requestId > 0)
        {
            model= await _leaveService.GetEditDetails(requestId);
        }
        
        model.Reasons = await _leaveService.GetReason();
        model.profile = await _profileService.GetUserDetails(email);
    
        ViewBag.LeaveType = new SelectList(await _leaveService.GetLeaveType(), "TypeId", "Type");
        return View(model);
    }

    [HttpPost]
    public async Task<IActionResult> AddEditLeaveRequest(AddLeaveRequestViewModel model)
    {   
        ResponseViewModel response;
        if (model.LeaveRequestId == 0)
        {
            response = await _leaveService.AddRequest(model);
        }
        else
        {
            response = await _leaveService.EditRequest(model);
        }

        if (response.success)
        {
            string notificationMessage = $"Add leave Request: {model.profile.Name} leave starting on {model.StartDate:dd/MM/yyyy}";
            response = await _leaveService.AddNotification(notificationMessage);
            await _hubContext.Clients.Group("Role_3").SendAsync("ReceiveNotification", notificationMessage);

            TempData["successToastr"] = response.message;
        }
        else
        {
            TempData["errorToastr"] = response.message;
        }

        return RedirectToAction("LeaveRequest");
    }

    [HttpPost]
    public async Task<IActionResult> DeleteLeaveRequest(int leaveRequestId)
    {
        ResponseViewModel response = await _leaveService.DeleteLeaveRequest(leaveRequestId);
        if(response.success)
        {
            TempData["successToastr"] = response.message;
        }
        else
        {
            TempData["errorToastr"] = response.message;
        }
        return RedirectToAction("LeaveRequest");
    }

    [HttpGet]
    public async Task<IActionResult> LeaveView(int leaveRequestId)
    {   
        var token = _jwtService.ValidateToken(Request.Cookies["token"]);
        var email = token?.Claims.FirstOrDefault(c => c.Type == ClaimTypes.Email)?.Value;
        if (email == null)
        {
           TempData["errorToastr"] = "Email not found.";
           return RedirectToAction("Index", "Home");
        }
        var model = await _leaveService.GetEditDetails(leaveRequestId);
        model.profile = await _profileService.GetUserDetails(email);        
        return PartialView("_LeaveViewPartialView", model);
    }
    
    #endregion

    #region Response  
    [CustomAuthorize ("HR")]
    public IActionResult ResponseRequest()
    {
        return View();
    }

    public async Task<IActionResult> GetResponseList(int pageSize, int pageNumber, string searchQuery, string sortColumn, string sortDirection, string leaveRequestFromDate, string leaveRequestToDate, string leaveRequestStatus,int employeeId)
    {   
        var model = await _leaveService.GetResponseData(pageSize, pageNumber, searchQuery, sortColumn, sortDirection, leaveRequestFromDate, leaveRequestToDate, leaveRequestStatus, employeeId);
        return PartialView("_ResponseLeaveRequestList", model);
    }

    [HttpGet]
    public async Task<IActionResult> ResponseLeaveRequest(int requestId)
    {
        AddLeaveRequestViewModel model = new AddLeaveRequestViewModel();
        model= await _leaveService.GetEditDetails(requestId);
        model.Reasons = await _leaveService.GetReason();
        model.profile = await _profileService.GetUserDetails(model.EmployeeEmail);
    
        ViewBag.LeaveType = new SelectList(await _leaveService.GetLeaveType(), "TypeId", "Type");
        return View(model);
    }

    [HttpPost]
    public async Task<IActionResult> ResponseLeaveRequest(int requestId, int statusId, int approvedBy, string comment)
    {
        ResponseViewModel response = await _leaveService.ResponseLeaveRequest(requestId, statusId, approvedBy, comment);

        var model = await _leaveService.GetEditDetails(requestId);

        if (string.IsNullOrEmpty(model.EmployeeId.ToString()))
        {
            TempData["errorToastr"] = "EmployeeId is missing.";
            return Json(new { success = false });
        }

        string notificationMessage = $"Your leave request has been {model.LeaveStatus} by {model.ApprovedBy}.";

        try
        {   
            response = await _leaveService.AddResponseNotification(notificationMessage, model.EmployeeId);
            await _hubContext.Clients.User(model.EmployeeId.ToString()).SendAsync("ReceiveNotification", notificationMessage);
        }
        catch (Exception ex)
        {
            Console.WriteLine($"Error sending notification: {ex.Message}");
        }

        if (response.success)
        {
            TempData["successToastr"] = response.message;
            return Json(new { success = true });
        }
        else
        {
            TempData["errorToastr"] = response.message;
            return Json(new { success = false });
        }
    }
    #endregion

    # region Excel
    public async Task<IActionResult> ExportExcelOfLeave(int pageSize, int pageNumber, string searchQuery, string leaveRequestFromDate, string leaveRequestToDate, string leaveRequestStatus, int employeeId)
    {
        var fileContent = await _leaveService.GetLeaveDataToExport(pageSize, pageNumber, searchQuery, leaveRequestFromDate, leaveRequestToDate, leaveRequestStatus, employeeId);
        return File(fileContent, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "LeaveRequest.xlsx");
    }

    public async Task<IActionResult> ExportExcelOfResponse(int pageSize, int pageNumber, string searchQuery, string leaveRequestFromDate, string leaveRequestToDate, string leaveRequestStatus, int employeeId)
    {
        var fileContent = await _leaveService.GetResponseDataToExport(pageSize, pageNumber, searchQuery, leaveRequestFromDate, leaveRequestToDate, leaveRequestStatus, employeeId);
        return File(fileContent, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "LeaveRequest.xlsx");
    }
    #endregion
}

Employee_Self_Service/Views/Shared/_Login_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] Employee_Self_Service</title>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" rel="stylesheet">
     <link rel="stylesheet" 
        href= "https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" rel="stylesheet"/>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
</head>
<body class="login">
        <main role="main" class="main mt-5">
            @RenderBody()
        </main>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await Html.PartialAsync("_TosterPartialView")
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Employee_Self_Service/Views/Shared/_NotificationPartialView.cshtml
@model List<Employee_Self_Service_DAL.ViewModel.NotificationViewModel>
@{
    string? employeeId = Context.Request.Cookies["EmployeeId"];
    string? userRole = Context.Request.Cookies["role"];
}

<li class="d-flex align-items-center justify-content-between align-items-center fw-bold text-secondary p-2">
    <span>Notifications(@Model.Select(u => u.NotificationId).Count())</span>
    <button type="button" class="btn-close fs-6" data-bs-dismiss="dropdown" aria-label="Close"
        id="addItemModelCancel"></button>
</li>
<hr class="dropdown-divider">
@foreach (var notification in Model)
{
    <li class="">
        <h6 class="px-2">@notification.NotificationCategory</h6>
        <div class="d-flex p-2 gap-2 ">
            @if (notification.NotificationCategory == "Event")
            {
                <a class="notificationEventDetails d-flex align-items-center text-decoration-none text-black" href=""
                    onclick="OpenEventModel(@notification.CategoryId, @notification.NotificationId)"
                    data-id="@notification.CategoryId" data-bs-toggle="modal" data-bs-target="#eventDetailsModal">
 
                    <span class="notificationMessage"
                        data-notificationid="@notification.NotificationId">@notification.Message</span>
                </a>
            }
            else if (notification.NotificationCategory == "Leave Request")
            {   
                <a class="leaveNotificationMessage d-flex align-items-center text-decoration-none text-black"
                    data-notificationid="@notification.NotificationId" asp-action="ResponseLeaveRequest" asp-controller="Leave"
                    asp-route-requestId="@notification.CategoryId">

                    <span>@notification.Message</span>
                </a>
                
            }
            else if (notification.NotificationCategory == "Response Request")
            {
                <span>@notification.Message</span>
            }
            else if (notification.NotificationCategory == "HelpDesk Request")
            {   
                if(userRole != "Employee"){
                <a class="helpDeskResponseNotificationMessage readMark d-flex align-items-center text-decoration-none text-black"
                    data-notificationid="@notification.NotificationId" asp-action="ResponseHelpDeskRequest" asp-controller="HelpDesk"
                    asp-route-requestId="@notification.CategoryId">

                    <span>@notification.Message</span>
                </a>
                }
                else{
                    <span>@notification.Message</span>
                }
                
            }
            <a class=" pb-1 "><i class="readMark read-icon bi bi-circle" data-notificationid="@notification.NotificationId"></i>
            </a>
        </div>
        <hr class="dropdown-divider">
    </li>
}
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script>

    $(".readMark").on('click', function (e) {
        e.stopPropagation();
        $.ajax({
            url: '/Notification/MarkRead',
            type: 'POST',
            data: {
                employeeId: @employeeId,
                notificationId: $(this).data("notificationid")
            },
            success: (response) => {
                if (!response.success) {
                    alert('Error in read mark');
                }
                NotificationDropdown();
                updateNotificationCount();
            },
            error: (error) => {
                alert('Error read mark notification. Please try again.');
            }
        })
    });

    function OpenEventModel(eventId, notificationId) {
        console.log("event details:" + eventId)
        $.ajax({
            url: '/Event/EventDetails',
            data: {
                eventId: eventId
            },
            type: "GET",
            success: function (data) {
                $("#eventDetailsModalContent").html(data);
                console.log("mark as read " + @employeeId + " and " + notificationId);
                $.ajax({
                    url: '/Notification/MarkRead',
                    type: 'POST',
                    data: {
                        employeeId: @employeeId,
                        notificationId: notificationId
                    },
                    success: (response) => {
                        if (!response.success) {
                            alert('Error in read mark on click message');
                        }
                        NotificationDropdown();
                        updateNotificationCount();
                    },
                    error: (error) => {
                        alert('Error read mark notification. Please try again.');
                    }
                })
            },
            error: function () {
                $("#eventDetailsModalContent").html('An error has occurred');
            }
        })
    }

    $(".leaveNotificationMessage").on('click', function (e) {
        e.stopPropagation();
        $.ajax({
            url: '/Notification/MarkRead',
            type: 'POST',
            data: {
                employeeId: @employeeId,
                'notificationId': $(this).data("notificationid")
            },
            success: (response) => {
                if (!response.success) {
                    alert('Error in read mark on click message');
                }
                NotificationDropdown();
                updateNotificationCount();
            },
            error: (error) => {
                alert('Error read mark notification. Please try again.');
            }
        })
    });

    $(".read-icon").hover(function (e) {
        $(this).hasClass("bi-circle") ? $(this).addClass("bi-check-circle text-primary").removeClass("bi-circle") : $(this).removeClass("bi-check-circle text-primary").addClass("bi-circle");
    });

    $(document).ready(function () {
        updateNotificationCount();
    });  
</script>

Employee_Self_Service/Views/Shared/_TosterPartialView.cshtml
<script type="text/javascript">
    
    $(document).ready(function() {
        toastr.options = {
            'closeButton': true,
            'debug': false,
            'newestOnTop': false,
            'progressBar': false,
            'positionClass': 'toast-top-right',
            'preventDuplicates': false,
            'showDuration': '1000',
            'hideDuration': '1000',
            'timeOut': '5000',
            'extendedTimeOut': '1000',
            'showEasing': 'swing',
            'hideEasing': 'linear',
            'showMethod': 'fadeIn',
            'hideMethod': 'fadeOut',
        }

        var successToastr = '@TempData["successToastr"]';
        var errorToastr = '@TempData["errorToastr"]';
        

        if(successToastr && successToastr.trim()!= "")
        {
            toastr.success(successToastr);
        }   

        if(errorToastr && errorToastr.trim()!= "")
        {
            toastr.error(errorToastr);
        }

    });

</script>