Employee_Self_Service/Controllers/HelpDeskController.cs
using System.Text.RegularExpressions;
using Employee_Self_Service.Authorization;
using Employee_Self_Service.Hubs;
using Employee_Self_Service_BAL.Interface;
using Employee_Self_Service_DAL.Constants;
using Employee_Self_Service_DAL.ViewModel;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.SignalR;
using static Employee_Self_Service_DAL.Constants.HelpDeskEnum;

namespace Employee_Self_Service.Controllers;

public class HelpDeskController : Controller
{
    private readonly IHelpDeskService _helpDeskService;
    private readonly IHubContext<NotificationHub> _hubContext;

    public HelpDeskController(IHelpDeskService helpDeskService, IHubContext<NotificationHub> hubContext)
    {
        _helpDeskService = helpDeskService;
        _hubContext = hubContext;
    }

    #region HelpDesk Request
    public IActionResult HelpDeskRequest()
    {
        return View();
    }

    [HttpGet]
    public async Task<IActionResult> GetRequestList(int pageSize, int pageNumber, string searchQuery, string sortColumn, string sortDirection, string helpDeskRequestGroup, string helpDeskRequestStatus, string leaveRequestStatus, int employeeId)
    {
        var model = await _helpDeskService.GetRequestData(pageSize, pageNumber, searchQuery, sortColumn, sortDirection, helpDeskRequestGroup, helpDeskRequestStatus, employeeId);
        return PartialView("_HelpDeskRequestListPartialView", model);
    }

    [HttpGet]
    public async Task<IActionResult> AddEditHelpdeskRequest(long requestId)
    {
        AddHelpDeskRequestViewModel model = new AddHelpDeskRequestViewModel
        {
            RequestedDate = DateTime.Now
        };
        if (requestId > 0)
        {
            model = await _helpDeskService.GetEditDetails(requestId);
            ViewBag.Groups = new SelectList(await _helpDeskService.GetGroups(), "GroupId", "GroupName", model.GroupId);
            ViewBag.Categories = new SelectList(await _helpDeskService.GetCategories(model.GroupId), "CategoryId", "CategoryName", model.CategoryId);
            ViewBag.SubCategories = new SelectList(await _helpDeskService.GetSubCategories(model.CategoryId), "SubCategoryId", "SubCategoryName", model.SubCategoryId);
        }

        ViewBag.PriorityList = Enum.GetValues(typeof(Priority))
            .Cast<Priority>()
            .Select(p => new SelectListItem
            {
                Value = p.ToString(), 
                Text = p.ToString()
            })
            .ToList();

        return View(model);
    }

    [HttpGet]
    public async Task<IActionResult> GetGroups()
    {
        var groups = await _helpDeskService.GetGroups();
        return Json(groups.Select(g => new { value = g.GroupId, text = g.GroupName }));
    }

    [HttpGet]
    public async Task<IActionResult> GetCategories(int groupId)
    {
        var categories = await _helpDeskService.GetCategories(groupId);
        return Json(categories.Select(c => new { value = c.CategoryId, text = c.CategoryName }));
    }

    [HttpGet]
    public async Task<IActionResult> GetSubCategories(int categoryId)
    {
        var subCategories = await _helpDeskService.GetSubCategories(categoryId);
        return Json(subCategories.Select(sc => new { value = sc.SubCategoryId, text = sc.SubCategoryName }));
    }

    [HttpPost]
    public async Task<IActionResult> AddEditHelpDeskRequest( AddHelpDeskRequestViewModel model)
    {

        ResponseViewModel response;
        if (model.HelpDeskRequestId == 0)
        {
            response = await _helpDeskService.AddRequest(model);
        }
        else
        {
            response = await _helpDeskService.EditRequest(model);
        }
        if (response.success)
        {   
           
            if(model.StatusId == 2)
            {
                string notificationMessage = $"HelpDesk Request Added By {model.EmployeeName} .";
                response = await _helpDeskService.AddNotificationByHr(notificationMessage);
                await _hubContext.Clients.Group("Role_4").SendAsync("ReceiveNotification", notificationMessage);
            }
            else
            {
            string notificationMessage = $"Add HelpDesk Request: {model.EmployeeName} Help of {model.Group}";
            response = await _helpDeskService.AddNotification(notificationMessage);
            await _hubContext.Clients.Group("Role_3").SendAsync("ReceiveNotification", notificationMessage);
            }

            TempData["successToastr"] = response.message;
            // return RedirectToAction("HelpDeskRequest");
            return Json(new { success = true });
        }
        else
        {
            TempData["errorToastr"] = response.message;
            // return RedirectToAction("AddEditHelpdeskRequest");
            return Json(new { success = true });
        }
    }

    [HttpPost]
    public async Task<IActionResult> DeleteHelpDeskRequest(long helpDeskRequestId)
    {
        ResponseViewModel response = await _helpDeskService.DeleteHelpDeskRequest(helpDeskRequestId);
        if (response.success)
        {
            TempData["successToastr"] = response.message;
        }
        else
        {
            TempData["errorToastr"] = response.message;
        }
        return RedirectToAction("HelpDeskRequest");
    }
    #endregion

    #region HelpDesk Response
    [CustomAuthorize ("HR","Network") ]
    public IActionResult HelpDeskResponse()
    {
        return View();
    }

    [HttpGet]
    public async Task<IActionResult> GetResponseList(int pageSize, int pageNumber, string searchQuery, string sortColumn, string sortDirection, string helpDeskResponseGroup, string helpDeskResponseStatus, int employeeId)
    {   
        string role = HttpContext.Request.Cookies["Role"];
        var model = await _helpDeskService.GetResponseData(pageSize, pageNumber, searchQuery, sortColumn, sortDirection, helpDeskResponseGroup, helpDeskResponseStatus, employeeId,role);
        return PartialView("_ResponseHelpDeskRequestList", model);
    }

    [HttpGet]
    public async Task<IActionResult> ResponseHelpDeskRequest(long requestId)
    {
        AddHelpDeskRequestViewModel model = new AddHelpDeskRequestViewModel();
        model = await _helpDeskService.GetEditDetails(requestId);

        ViewBag.PriorityList = Enum.GetValues(typeof(Priority))
            .Cast<Priority>()
            .Select(p => new SelectListItem
            {
                Value = p.ToString(),
                Text = p.ToString()
            })
            .ToList();

        return View(model);
    }

    [HttpPost]
    public async Task<IActionResult> ResponseHelpDeskRequest(AddHelpDeskRequestViewModel model)
    {
        ResponseViewModel response = await _helpDeskService.ResponseHelpDeskRequest(model);

        var detail = await _helpDeskService.GetEditDetails(model.HelpDeskRequestId);

        if (response.success)
        {

            if (detail.StatusId == 2)
            {
                string notificationMessage = $"HelpDesk Request Added By {detail.InsertedBy} and Approved By {model.EmployeeName}.";
                response = await _helpDeskService.AddNotificationByHr(notificationMessage);
                await _hubContext.Clients.Group("Role_4").SendAsync("ReceiveNotification", notificationMessage);
                response = await _helpDeskService.AddResponseNotification(notificationMessage, detail.EmployeeId);
                await _hubContext.Clients.User(detail.EmployeeId.ToString()).SendAsync("ReceiveNotification", notificationMessage);
            }
            if (detail.StatusId == 7)
            {
                string notificationResponseMessage = $"HelpDesk Request is Reject and Rejected By {model.EmployeeName}.";
                response = await _helpDeskService.AddResponseNotification(notificationResponseMessage, detail.EmployeeId);
                await _hubContext.Clients.User(detail.EmployeeId.ToString()).SendAsync("ReceiveNotification", notificationResponseMessage);
            }
            if(detail.StatusId == 1)
            {
                string notificationResponseMessage = $"HelpDesk Request is Acknowledge and Acknowledge By {model.EmployeeName}.";
                response = await _helpDeskService.AddResponseNotification(notificationResponseMessage, detail.EmployeeId);
                await _hubContext.Clients.User(detail.EmployeeId.ToString()).SendAsync("ReceiveNotification", notificationResponseMessage);
            }
            if(detail.StatusId == 4)
            {
                string notificationResponseMessage = $"HelpDesk Request is Close and Closed By {model.EmployeeName}.";
                response = await _helpDeskService.AddResponseNotification(notificationResponseMessage, detail.EmployeeId);
                await _hubContext.Clients.User(detail.EmployeeId.ToString()).SendAsync("ReceiveNotification", notificationResponseMessage);
            }
            if(detail.StatusId == 3)
            {
                string notificationResponseMessage = $"HelpDesk Request is Cancel and Cancel By {model.EmployeeName}.";
                response = await _helpDeskService.AddResponseNotification(notificationResponseMessage, detail.EmployeeId);
                await _hubContext.Clients.User(detail.EmployeeId.ToString()).SendAsync("ReceiveNotification", notificationResponseMessage);
            }

            TempData["successToastr"] = response.message;
            return Json(new { success = true });
        }
        else
        {
            TempData["errorToastr"] = response.message;
            return Json(new { success = false });
        }
    }

    [HttpGet]
    public async Task<IActionResult> GetStatusHistory(long requestId)
    {
        var history = await _helpDeskService.GetStatusHistory(requestId); 
        return PartialView("_StatusHistoryPartialView", history);
    }
    #endregion

    #region HelpDesk Excel

Employee_Self_Service/Views/HelpDesk/HelpDeskRequest.cshtml
@{
    Layout = "_Layout";
    
}   
@{
    string? employeeId = Context.Request.Cookies["EmployeeId"];
}
<div class="container-fluid ">
    <div class="row  p-0 justify-content-sm-between orders col ">
        <div class="d-flex flex-column py-3 px-1">
            <div class="px-1 d-flex justify-content-between align-items-center">
                <div>
                    <h6>Helpdesk</h6>
                    <h4 class=" d-flex align-content-center m-0">Self Requests</h4>
                </div>

                <a href="/HelpDesk/AddEditHelpdeskRequest" class="text-dark"><i class="bi bi-plus-square-fill fs-2"></i></a>
            </div>
            <hr class="dropdown-divider">
        </div>

        <div class="d-flex flex-column flex-xl-row gap-2 justify-content-start align-content-end mb-3">
            <div class="row col ">
                <div class="ticketSelection  px-2 my-1 my-lg-0 col-sm-6 col-md-5 col-lg-6 col-xl-2  col-12">
                    <label for="itemName" class=" mb-1">Ticket #</label>
                    <input type="text" class=" form-control rounded-0 shadow-none border-2" id="helpDeskSearchInput" >
                </div>
                
                <div class="groupSelection re px-2 my-1 my-lg-0 col-sm-6 col-md-5 col-lg-6 col-xl-2 ">
                    <label for="itemName" class=" mb-1 ">Group</label>
                    <select class="form-select  rounded-0 border-2 shadow-none" id="helpDeskRequestGroup">
                        <option value="0" selected>All</option>
                        <option value="1">Networking</option>
                    </select>
                </div>

                <div class="statusSelection re px-2 my-1 my-lg-0 col-sm-6 col-md-5 col-lg-6 col-xl-2 ">
                    <label for="itemName" class=" mb-1 ">Status</label>
                    <select class="form-select  rounded-0 border-2" id="helpDeskRequestStatus">
                        <option value="0">All</option>
                        <option value="1">Acknowledged</option>
                        <option value="2">Approved</option>
                        <option value="3">Cancel</option>
                        <option value="4" >Closed</option>
                        <option value="5" >Hold</option>
                        <option value="6" selected>Pending</option>
                        <option value="7">Rejected</option>
                    </select>
                </div>

                <div class="d-flex align-items-end  col-12 col-xl-3 col-lg-6 col-xl-2 mt-3 gap-2">
                    <a class="btn btn-primary rounded-0  px-4" style="background-color:#0066a7" id="searchSelfHelpDeskRequest">
                        Search
                    </a>
                    <a class="btn cancle_btn clear rounded-0 ms-2 px-4 border-primary text-primary fw-semibold">
                        Reset
                    </a>
                    <a class="btn w-auto my-1 my-lg-0 ms-1 d-flex align-items-center justify-content-center text-white"
                        id="exportHelpDeskBtn" style="background-color:#0066a7">
                        <i class="fa-solid fa-share-from-square me-2"></i>
                        Export
                    </a>
                </div>
            </div>
        </div>

        <div id="helpDeskRequestTableList" class="table_container">

        </div>
    </div>
</div>

<div class="modal fade " id="deleteHelpDeskModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered text-secondary">
        <div class="modal-content">
            <div class="modal-header border border-0">
                <h5 class="modal-title" id="exampleModalLabel">Delete Confiremation</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body d-flex justify-content-center flex-column align-items-center">
                <img src="../images/toppng.com-warning-icon-2400x2400.png" alt="" style="width: 70px">
                <p>Are you sure you want to cancel this HelpDesk Request?</p>
            </div>
            <div class="modal-footer border border-0 d-flex justify-content-center">
                <form asp-action="DeleteHelpDeskRequest" asp-controller="HelpDesk">
                    <input type="hidden" name="helpDeskRequestId" id="HelpDeskRequestId" value="">
                    <button type="submit" class="confirmLeaveDeleteBtn btn btn-primary"
                        id="confirmLeaveDeleteBtn">YES</button>
                    <button type="button" class="btn btn-outline-primary" data-bs-dismiss="modal">NO</button>
                </form>
            </div>
        </div>
    </div>
</div>

<script src="~/lib/jquery/dist/jquery.min.js"></script>

<script>
    let sortColumn = '';
    let sortDirection = 'asc';

    function HelpDeskRequestPaginationAjax(pageNumber) {
        let pageSize = $("#helpDeskRequestPageSize").val();
        if (pageSize == 0 || pageSize == null) pageSize = 5;
        if (pageNumber === 0) pageNumber = 1;
        var searchQuery = $('#helpDeskSearchInput').val() || '';
        if (pageNumber === 0) {
            pageNumber = @((Model?.Page!.CurrentPage ?? 1));
        }
       
        let helpDeskRequestGroup = $('#helpDeskRequestGroup').val();
        let helpDeskRequestStatus = $('#helpDeskRequestStatus').val();
        
        $.ajax({
            url: "/HelpDesk/GetRequestList",
            data: {
                pageSize: pageSize,
                pageNumber: pageNumber,
                searchQuery: searchQuery,
                sortColumn: sortColumn,
                sortDirection: sortDirection,
                helpDeskRequestGroup: helpDeskRequestGroup,
                helpDeskRequestStatus: helpDeskRequestStatus,
                employeeId: @employeeId
            },
            type: "GET",
            dataType: "html",
            success: function (data) {
                console.log("Hello");
                $("#helpDeskRequestTableList").html(data);
            },
            error: function () {
                alert("No Projects Found");
                $("#helpDeskRequestTableList").html('An error has occurred');
            }
        });
    }

    function sortBy(column) {
        if (sortColumn === column) {
            sortDirection = sortDirection === 'asc' ? 'desc' : 'asc';
        } else {
            sortDirection = 'asc';
        }
        sortColumn = column;
        HelpDeskRequestPaginationAjax(1);
    }

    $('#searchSelfHelpDeskRequest').click(function () {
        HelpDeskRequestPaginationAjax(1);
    });

    $(document).ready(function () {
        HelpDeskRequestPaginationAjax(1);
    });
   

    $(document).on("click", ".cancle_btn", function () {
        $("#helpDeskSearchInput").val("");
        $("#helpDeskRequestGroup").val(0);
        $('#helpDeskRequestStatus').val(6);
        HelpDeskRequestPaginationAjax(1);
    })

    /* -------------------------------------------------------------------------------------Delete HelpDesk Request Script --------------------------------------------------------*/
    $(document).on("click", ".deleteHelpDeskBtn", function () {
        let helpDeskRequestId = $(this).data("id");
        $('#HelpDeskRequestId').val(helpDeskRequestId);
    });

    /* -------------------------------------------------------------------------------------Export Event Script --------------------------------------------------------*/
    $('#exportHelpDeskBtn').on('click', function () {    
        let pageNumber =1;
        let pageSize = $("#helpDeskRequestPageSize").val();
        if (pageSize == 0 || pageSize == null) pageSize = 5;
        if (pageNumber === 0) pageNumber = 1;
        var searchQuery = $('#helpDeskSearchInput').val() || '';
        let helpDeskGroup = $('#helpDeskRequestGroup').val();
        let helpDeskStatus = $('#helpDeskRequestStatus').find('option:selected').text();
        
        $.ajax({
            url: "/HelpDesk/ExportExcelOfHelpDesk",
            data: {
                pageSize: pageSize,
                pageNumber: pageNumber,
                searchQuery: searchQuery,
                helpDeskGroup: helpDeskGroup,
                helpDeskStatus: helpDeskStatus,
                employeeId: @employeeId              
            },
            xhrFields: {
                responseType: 'blob'
            },
            type: "POST",
            success: function (data) {
                
                let blob = new Blob([data], { type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" });
               
                var isIE = false || !!document.documentMode;
                if (isIE) {
                    window.navigator.msSaveBlob(blob, "HelpDeskRequestList.xlsx");
                } else {
                    var url = window.URL || window.webkitURL;
                    link = url.createObjectURL(blob);
                    var a = $("<a />");
                    a.attr("download", "HelpDeskRequestList.xlsx");
                    a.attr("href", link);
                    $("body").append(a);
                    a[0].click();
                    $("body").remove(a);
                }

            },
            error: function () {

            }
        });
    });

</script>

Employee_Self_Service/Views/HelpDesk/_HelpDeskRequestListPartialView.cshtml
@model Employee_Self_Service_DAL.ViewModel.HelpDeskPaginationViewModel
@using Employee_Self_Service.DAL.Attributes
@using Employee_Self_Service_DAL.ViewModel
@using System.Reflection

<div class="table-responsive px-0">

    <table class="table">
        <thead>
            <tr class="">
                @{
                    var props = typeof(Employee_Self_Service_DAL.ViewModel.HelpDeskDetailsViewModel).GetProperties();

                }
                @foreach (var prop in props)
                {
                    var displayAttr = prop.GetCustomAttribute<DisplayColumnAttribute>();

                    if (displayAttr != null && displayAttr.IsVisible)
                    {
                        <th class="@(prop.PropertyType == typeof(DateTime) ? "" : "text-center")" style="white-space: nowrap;">
                            <a href="javascript:void(0)" onclick="sortBy('@prop.Name')"
                                class="text-decoration-none text-dark">@displayAttr.Name
                                <i class="bi bi-arrow-down-up" id="sort-by-@prop.Name.Replace('.', '-')"
                                    data-direction="asc"></i>
                            </a>
                        </th>
                    }
                }
                <th class="text-center" style="white-space: nowrap;">Action</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var data in Model.HelpDeskList)
            {
                <tr>
                    @foreach (var prop in props)
                    {
                        var displayAttr = prop.GetCustomAttribute<DisplayColumnAttribute>();

                        if (displayAttr != null && displayAttr.IsVisible)
                        {
                            var value = prop.GetValue(data);
                            <td class="text-center">
                                @if (prop.Name == "Status")
                                {
                                    <span class="badge status @(data.StatusId switch
                                {
                                2 => "approved",
                                7 => "rejected",
                                3 => "cancelled",
                                1 => "acknowledged",
                                4 => "closed",
                                _ => "pending"
                                }) p-2 text-black fw-lighter fs-6">
                                        @value
                                    </span>
                                }
                                else if (prop.Name == "HelpDeskRequestId")
                                {
                                    @if (data.PendingAt.ToString() != "HR" && data.StatusId != 3)
                                    {
                                        <a asp-action="ResponseHelpDeskRequest" asp-controller="HelpDesk"
                                            asp-route-requestId="@data.HelpDeskRequestId">
                                            @data.HelpDeskRequestId
                                        </a>
                                    }
                                    else
                                    {
                                        @data.HelpDeskRequestId
                                    }
                                }
                                else if (prop.Name == "Priority")
                                {
                                    <span class="badge status @(data.Priority.ToString().ToLower()) p-2 text-black fw-lighter fs-6">
                                        @value
                                    </span>
                                }
                                else if (value is IEnumerable<string> subCats)
                                {
                                    foreach (var item in subCats ?? Enumerable.Empty<string>())
                                    {
                                        @item

                                        <br />
                                    }
                                }
                                else if (value is DateTime dt)
                                {
                                    @dt.ToString("dd-MMM-yyyy hh:mm tt")
                                }
                                else
                                {
                                    @value
                                }
                            </td>
                        }
                    }
                    <td class="text-center">
                        <div class="d-flex justify-content-center align-items-center">
                            @if (data.PendingAt == "HR")
                            {
                                <a asp-action="AddEditHelpdeskRequest" asp-controller="HelpDesk"
                                    asp-route-requestId="@data.HelpDeskRequestId" class="btn">
                                    <i class="bi bi-pen"></i>
                                </a>
                                <a class="btn deleteHelpDeskBtn p-0" data-id="@data.HelpDeskRequestId" data-bs-toggle="modal"
                                    data-bs-target="#deleteHelpDeskModal">
                                    <i class="bi bi-trash text-black"></i>
                                </a>
                            }
                            else
                            {
                                <a asp-action="ResponseHelpDeskRequest" asp-controller="HelpDesk"
                                    asp-route-requestId="@data.HelpDeskRequestId" class="btn">
                                    <i class="fa-solid fa-pen-to-square"></i>
                                </a>
                            }
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

<!-- Pagination Section -->
<div class="d-flex flex-row justify-content-end gap-2 mb-3 align-items-center">
    <p class="pt-3 text-black">Items per page</p>
    <div class="dropdown">
        <select class="form-select w-auto" onchange="HelpDeskRequestPaginationAjax(@Model.Page.CurrentPage)"
            aria-label="Default select example" id="helpDeskRequestPageSize">
            @if (Model.Page.PageSize != null)
            {
                <option value="5" selected="@(Model.Page.PageSize == 5 ? "selected" : null)">5</option>
                <option value="10" selected="@(Model.Page.PageSize == 10 ? "selected" : null)">10</option>
                <option value="15" selected="@(Model.Page.PageSize == 15 ? "selected" : null)">15</option>
            }
        </select>
    </div>
    <p class="pt-3 text-black">Showing @Model.Page!.FromRec - @Model.Page.ToRec of @Model.Page.TotalRecord</p>

    <!-- Previous Button -->
    <button class="btn btn-outline-primary col-auto"
        onclick="HelpDeskRequestPaginationAjax(@Model.Page.CurrentPage - 1)" @(Model.Page.CurrentPage > 1 ? "" :
        "disabled")> &lt; </button>

    <!-- Next Button -->
    <button class="btn btn-outline-primary col-auto"
        onclick="HelpDeskRequestPaginationAjax(@Model.Page.CurrentPage + 1)" @(Model.Page.CurrentPage <
        Model.Page.TotalPages ? "" : "disabled")> &gt; </button>
</div>

<script src="~/lib/jquery/dist/jquery.min.js"></script>

Employee_Self_Service/Views/HelpDesk/_StatusHistoryPartialView.cshtml
@model List<Employee_Self_Service_DAL.ViewModel.StatusHistoryViewModel>

<h4>Request Status History</h4>  
<div class="table-responsive px-0 ">
    <div class="border">
        <table class="table table-bordered mb-0">
            <thead>
                <tr>
                    <th class="text-center">
                        Name

                    </th>
                    <th>
                        Status Changed Date
                        Date
                    </th>
                    <th class="text-center">
                        Status
                    </th>

                    <th class="text-center">
                        Comments
                    </th>

                </tr>

            </thead>

            <tbody>
                @foreach (var data in Model)
                {
                    <tr>
                        <td class="text-center">
                            @data.Name
                        </td>
                        <td class="">@data.StatusChangedDate</td>
                        <td class="text-center">
                            @data.Status
                        </td>
                        <td class="text-center">
                            @data.Comment
                        </td>
                    </tr>
                }

            </tbody>
            
        </table>
        @if (@Model == null || !@Model.Any())
        {
        <h6 class="text-secondary text-center ">No Record Found</h6>
        }
    </div>
</div>